# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'sudhakar678/Mini-project-'
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'Testconnection-sonarqube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'test'
    cliProjectName: 'ENG_UI_Twist'
    cliSources: 'sudhakar678 / Mini-project-'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'sudhakar678 / Mini-project-'
    customCommand: 'run build'